## Copying by Reference

In [29]:
import numpy as np

In [30]:
list1 = [[1,2,3,4],[5,6,7,8]]
a1 = np.array(list1)
print(a1)

[[1 2 3 4]
 [5 6 7 8]]


In [24]:
a2 = a1

In [34]:
a2[0,0] = 1
print(a1)
print()
a1.shape = 1,-1
print(a1)
print(a2)

[[1 2 3 4 5 6 7 8]]

[[1 2 3 4 5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]


In [35]:
a2 = a1.view()

In [36]:
a1.shape = 1,-1

In [37]:
print(a2)

[[1 2 3 4 5 6 7 8]]
