In [1]:
import numpy as np

In [2]:
x1 = np.array([[1,2,3],[4,5,6]])
y1 = np.array([[7,8,9],[2,3,4]])

### Adding!!

In [4]:
#prints each individual element in a one to one way
print(x1 + y1)

[[ 8 10 12]
 [ 6  8 10]]


In [5]:
x = np.array([2,3])
y = np.array([4,2])
z = x + y
print(z)

[6 5]


### Subtracting

In [6]:
#same thing as adding, but subtraction
print(x1 - y1)

[[-6 -6 -6]
 [ 2  2  2]]


### Multiplying and Dividing

In [12]:
#again, works the same as adding and subtracting
print(x1 * y1)
print(x1 / y1)

[[ 7 16 27]
 [ 8 15 24]]
[[0.14285714 0.25       0.33333333]
 [2.         1.66666667 1.5       ]]


In [13]:
names = np.array(['Ann','Joe','Mark'])
heights = np.array([1.5,1.78,1.6])
weights = np.array([65,46,59])

bmi = weights/heights **2

In [14]:
print("Overweight: ", names[bmi>25])

Overweight:  ['Ann']
