In [1]:
#This is a python list
list1 = [1,2,3,4,5]

In [2]:
#Python lists can store more than 1 data type
list2 = [1,"Hello",3.14,True,5]

# Creating NumPy Arrays

In [3]:
import numpy as np

Create an evenly spaced NumPy array

In [4]:
#name = np.arange(beginning,endNonInclusive,steps)
a1 = np.arange(5,15,2)
print(a1)
print(a1.shape)

[ 5  7  9 11 13]
(5,)


Create an array of a specified size filled with zeroes.

In [5]:
a3 = np.zeros(5)
print(a3)
print(a3.shape)
print()

a4 = np.zeros((2,3))
print(a4.shape)
print(a4)

[0. 0. 0. 0. 0.]
(5,)

(2, 3)
[[0. 0. 0.]
 [0. 0. 0.]]


Array filled with a specific number

In [6]:
a5 = np.full(6, 8)
a5 = np.full((2,3),8)

Create an Identity Matrices

In [7]:
a6 = np.eye(4)
print(a6)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Create an array filled with random numbers

In [8]:
a7 = np.random.random(4)
print(a7)

[0.37558176 0.89697283 0.23988853 0.15092453]


Create a NumPy array from a python list

In [9]:
list1 = [1,2,3,4,5]
r1 = np.array(list1)
print(r1)

[1 2 3 4 5]
