In [3]:
import numpy as np
x2 = np.matrix([[1,2],[4,5]])
y2 = np.matrix([[7,8],[2,3]])
print(x2 * y2)

[[11 14]
 [38 47]]


# Cumulative Sum

In [6]:
#cumulative sum of all numbers, row by row
a = np.array([(1,2,3),(4,5,6),(7,8,9)])
print(a)
print(a.cumsum())
#first, first + second, first + second + third... etc

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 1  3  6 10 15 21 28 36 45]


In [7]:
#cumulative sum of colums
print(a.cumsum(axis=0))

[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]


In [8]:
#cumulative sum of rows
print(a.cumsum(axis=1))

[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]
