In [1]:
import numpy as np

In [7]:
ages = np.array([34,12,37,5,13,459])

In [3]:
sorted_ages = np.sort(ages)

In [4]:
print(sorted_ages)

[ 5 12 13 34 37]


In [8]:
print(ages)
#argsort returns an array of indeces of elements of the original array that will sort the array,
print(ages.argsort())

[ 34  12  37   5  13 459]
[3 1 4 0 2 5]


In [10]:
persons = np.array(['Johnny','Mary','Peter','Will','Joe'])
ages = np.array([34,12,37,5,13])
heights = np.array([1.76,1.2,1.68,0.5,1.25])

In [12]:
sort_indeces = np.argsort(ages)
#we want to sort everything by ages

print(ages[sort_indeces])
print(persons[sort_indeces])
print(heights[sort_indeces])

[ 5 12 13 34 37]
['Will' 'Mary' 'Joe' 'Johnny' 'Peter']
[0.5  1.2  1.25 1.76 1.68]
