In [13]:
import numpy as np
b5 = np.array([9,8,7,6,5,4,3,2,1,0])

Let's reshape the b5 array from a 1D array to a 2D array

In [26]:
b5 = b5.reshape(2,-1)
print(b5)
print(b5.shape)

[[9 8 7 6 5]
 [4 3 2 1 0]]
(2, 5)


How to make a rank 2 array to a rank 1 array

In [28]:
b5 = b5.reshape(-1,)
print(b5)

[9 8 7 6 5 4 3 2 1 0]
