In [1]:
import numpy as np

In [2]:
a = np.array([
    [1,2,3,4,5],
    [4,5,6,7,8],
    [9,7,6,5,4]
])

In [3]:
b1 = a[1:3, :3]
print(b1)

[[4 5 6]
 [9 7 6]]


In [10]:
b2 = np.array([0,1,2,3,4,5,6,7,8,9])
print(b2[:3])

[0 1 2]


In [11]:
print(a[-2:,-2:])

[[7 8]
 [5 4]]


Array splicing returns a reference to original array, so if you change the value of the spliced array you change the value of the original array

In [13]:
b1[0,0] = 10000000

In [14]:
print(a)

[[       1        2        3        4        5]
 [10000000        5        6        7        8]
 [       9        7        6        5        4]]
